// <auto-generated />
using System;
using LootSingles.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LootSingles.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LootSinglesDbContext))]
    [Migration("20260921155303_AddPackingHandoff")]
    partial class AddPackingHandoff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LootSingles.Application.Import.ImportAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttemptFailureCode")
                        .HasColumnType("int");

                    b.Property<string>("AttemptFailureMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ImportAttempts");
                });

            modelBuilder.Entity("LootSingles.Application.Import.ImportOrderResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FailureCode")
                        .HasColumnType("int");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImportAttemptId")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int?>("ResultingOrderId")
                        .HasColumnType("int");

                    b.Property<string>("SourceOrderIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImportAttemptId");

                    b.HasIndex("ResultingOrderId");

                    b.ToTable("ImportOrderResults");
                });

            modelBuilder.Entity("LootSingles.Domain.Employees.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LootSingles.Domain.Employees.EmployeeAuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActorEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("TargetEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorEmployeeId");

                    b.HasIndex("TargetEmployeeId");

                    b.ToTable("EmployeeAuditEvents");
                });

            modelBuilder.Entity("LootSingles.Domain.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ClaimedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PackedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PackedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TcgplayerOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedByEmployeeId")
                        .IsUnique()
                        .HasFilter("[ClaimedByEmployeeId] IS NOT NULL");

                    b.HasIndex("PackedByEmployeeId");

                    b.HasIndex("TcgplayerOrderId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LootSingles.Domain.Orders.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentPickingIssueId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("PickOutcome")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PickOutcomeRecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PickOutcomeRecordedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ProductLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Rarity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Variant")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPickingIssueId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PickOutcomeRecordedByEmployeeId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("LootSingles.Domain.Orders.OrderPackingSlip", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset>("StoredAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OrderId");

                    b.ToTable("OrderPackingSlips");
                });

            modelBuilder.Entity("LootSingles.Domain.Orders.PackingSlipAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrderId", "RetrievedAt");

                    b.ToTable("PackingSlipAccesses");
                });

            modelBuilder.Entity("LootSingles.Domain.Orders.PickingIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FoundQuantity")
                        .HasColumnType("int");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderLineId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ReportedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderLineId");

                    b.HasIndex("ReportedByEmployeeId");

                    b.ToTable("PickingIssues");
                });

            modelBuilder.Entity("LootSingles.Application.Import.ImportOrderResult", b =>
                {
                    b.HasOne("LootSingles.Application.Import.ImportAttempt", null)
                        .WithMany("ImportOrderResults")
                        .HasForeignKey("ImportAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LootSingles.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("ResultingOrderId");
                });

            modelBuilder.Entity("LootSingles.Domain.Orders.Order", b =>
                {
                    b.HasOne("LootSingles.Domain.Employees.Employee", "ClaimedByEmployee")
                        .WithMany()
                        .HasForeignKey("ClaimedByEmployeeId");

                    b.HasOne("LootSingles.Domain.Employees.Employee", "PackedByEmployee")
                        .WithMany()
                        .HasForeignKey("PackedByEmployeeId");

                    b.Navigation("ClaimedByEmployee");

                    b.Navigation("PackedByEmployee");
                });

            modelBuilder.Entity("LootSingles.Domain.Orders.OrderLine", b =>
                {
                    b.HasOne("LootSingles.Domain.Orders.PickingIssue", "CurrentPickingIssue")
                        .WithMany()
                        .HasForeignKey("CurrentPickingIssueId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LootSingles.Domain.Orders.Order", null)
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LootSingles.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("PickOutcomeRecordedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentPickingIssue");
                });

            modelBuilder.Entity("LootSingles.Domain.Orders.OrderPackingSlip", b =>
                {
                    b.HasOne("LootSingles.Domain.Orders.Order", "Order")
                        .WithOne()
                        .HasForeignKey("LootSingles.Domain.Orders.OrderPackingSlip", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LootSingles.Domain.Orders.PackingSlipAccess", b =>
                {
                    b.HasOne("LootSingles.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LootSingles.Domain.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LootSingles.Domain.Orders.PickingIssue", b =>
                {
                    b.HasOne("LootSingles.Domain.Orders.OrderLine", null)
                        .WithMany()
                        .HasForeignKey("OrderLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LootSingles.Domain.Employees.Employee", "ReportedByEmployee")
                        .WithMany()
                        .HasForeignKey("ReportedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportedByEmployee");
                });

            modelBuilder.Entity("LootSingles.Application.Import.ImportAttempt", b =>
                {
                    b.Navigation("ImportOrderResults");
                });

            modelBuilder.Entity("LootSingles.Domain.Orders.Order", b =>
                {
                    b.Navigation("OrderLines");
                });
#pragma warning restore 612, 618
        }
    }
}
